name: web_shopping
description: "New style Web Shopping"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  firebase_storage: ^11.7.4
  flutter:
    sdk: flutter
  http: ^1.2.1
  image_picker: ^1.1.1
  path: ^1.9.0
  preload_page_view: ^0.2.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  uuid: ^4.4.0
  video_player: ^2.8.6
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: noto-sans
      fonts:
        - asset: assets/fonts/NotoSansKR-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansKR-SemiBold.ttf
          weight: 200
        - asset: assets/fonts/NotoSansKR-Regular.ttf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Medium.ttf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Light.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR-ExtraLight.ttf
          weight: 600
        - asset: assets/fonts/NotoSansKR-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansKR-Black.ttf
          weight: 900
    - family: Fontello
      fonts:
        - asset: assets/fonts/fontello.ttf