// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJHF8laqO4Za-Zhg_RwlVOxolOiAoxtks',
    appId: '1:141249426301:web:441b94c55329418c705214',
    messagingSenderId: '141249426301',
    projectId: 'veno-shop',
    authDomain: 'veno-shop.firebaseapp.com',
    storageBucket: 'veno-shop.appspot.com',
    measurementId: 'G-1V8N17X4TF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUBjNHrNiDwNGtdV5uhK9Rqm6RDXeWWas',
    appId: '1:141249426301:android:081cdeaae908b17f705214',
    messagingSenderId: '141249426301',
    projectId: 'veno-shop',
    storageBucket: 'veno-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTvwq0zkC65O99fgVmzR8vq1W3DB4O4fY',
    appId: '1:141249426301:ios:7251dbb9130a87c8705214',
    messagingSenderId: '141249426301',
    projectId: 'veno-shop',
    storageBucket: 'veno-shop.appspot.com',
    iosBundleId: 'kr.veno.webshopping.webShopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTvwq0zkC65O99fgVmzR8vq1W3DB4O4fY',
    appId: '1:141249426301:ios:7251dbb9130a87c8705214',
    messagingSenderId: '141249426301',
    projectId: 'veno-shop',
    storageBucket: 'veno-shop.appspot.com',
    iosBundleId: 'kr.veno.webshopping.webShopping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJHF8laqO4Za-Zhg_RwlVOxolOiAoxtks',
    appId: '1:141249426301:web:0a4a2a5b44397ff9705214',
    messagingSenderId: '141249426301',
    projectId: 'veno-shop',
    authDomain: 'veno-shop.firebaseapp.com',
    storageBucket: 'veno-shop.appspot.com',
    measurementId: 'G-FJJJG5LVVQ',
  );
}
